spring:
  application:
    name: feed-svc

  config:
    activate:
      on-profile: docker

  grpc:
    client:
      channel:
        social:
          target: static://social-svc:9093

        content:
          target: static://content-svc:9091

app:
  jwt:
    secret: asdfjhsadfuyqweuryqwyer987qweroiqwuefohsakjdhfsaheiufyqwer

server:
  port: 8086