### зарегаться
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "email": "wxrst4@gmail.com",
  "username": "wxrst",
  "password": "wxrst"
}

<> 2026-08-17T173715.200.json

### обновить токен
POST http://localhost:8080/api/v1/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ3eHJzdCIsInVzZXJJZCI6ImI1ODliZGIyLTQ5YTYtNDczYS1iZDQzLTg0NzA2ZGEwMGNjYyIsImlhdCI6MTc4Njk3NzQzNSwiZXhwIjoxNzg5NTY5NDM1fQ.tDUTGs_IfveMDZCaGNVfbXro15EXHGmrzLOtveFU0fpVZLIlWBBtDEGxjLhVwlnj"
}

### создать канал
POST http://localhost:8082/api/v1/channels
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ3eHJzdCIsInVzZXJJZCI6ImI1ODliZGIyLTQ5YTYtNDczYS1iZDQzLTg0NzA2ZGEwMGNjYyIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpYXQiOjE3ODY5Nzc0MzUsImV4cCI6MTc4Njk3NzUyNX0.nkDpppBaaxlS16ZjqqdJthV6FKx5Tg0C7uD5AhzkJl35ZDVJYKA-v6kSljjdYtk6

{
  "name": "Java",
  "description": "Java develop"
}

<> 2026-08-17T173753.200.json

### создать пост
POST http://localhost:8082/api/v1/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ3eHJzdCIsInVzZXJJZCI6ImI1ODliZGIyLTQ5YTYtNDczYS1iZDQzLTg0NzA2ZGEwMGNjYyIsImlhdCI6MTc4Njk3NzU1MywiZXhwIjoxNzg5NTY5NTUzfQ.ASch-ROg2ByNZ_SOXaDCu-zaF41zGn-jYUfjIu9EAoSw63Hv41K1ie4gD-xRr4bc

{
  "channelId": "0af76998-a5bd-42e3-9cc8-678810463d1c",
  "title": "Java Core",
  "content": "Start learnin java core"
}



<> 2026-08-17T173934.200.json
<> 2026-08-17T173913.200.json

### отправить пост на модерацию
POST http://localhost:8082/api/v1/posts/5bcc9f4b-b9c2-43f9-8767-3135fd4a39a9/moderation
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ3eHJzdCIsInVzZXJJZCI6ImI1ODliZGIyLTQ5YTYtNDczYS1iZDQzLTg0NzA2ZGEwMGNjYyIsImlhdCI6MTc4Njk3NzU1MywiZXhwIjoxNzg5NTY5NTUzfQ.ASch-ROg2ByNZ_SOXaDCu-zaF41zGn-jYUfjIu9EAoSw63Hv41K1ie4gD-xRr4bc

<> 2026-08-17T174020.200.json

### опубликать пост в канале
POST http://localhost:8082/api/v1/posts/5bcc9f4b-b9c2-43f9-8767-3135fd4a39a9/publish
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ3eHJzdCIsInVzZXJJZCI6ImI1ODliZGIyLTQ5YTYtNDczYS1iZDQzLTg0NzA2ZGEwMGNjYyIsImlhdCI6MTc4Njk3NzU1MywiZXhwIjoxNzg5NTY5NTUzfQ.ASch-ROg2ByNZ_SOXaDCu-zaF41zGn-jYUfjIu9EAoSw63Hv41K1ie4gD-xRr4bc

<> 2026-08-17T174039.200.json

### подписаться на канал
POST http://localhost:8083/api/v1/subscriptions/channels/0af76998-a5bd-42e3-9cc8-678810463d1c/subscribe
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ3eHJzdCIsInVzZXJJZCI6ImI1ODliZGIyLTQ5YTYtNDczYS1iZDQzLTg0NzA2ZGEwMGNjYyIsImlhdCI6MTc4Njk3NzU1MywiZXhwIjoxNzg5NTY5NTUzfQ.ASch-ROg2ByNZ_SOXaDCu-zaF41zGn-jYUfjIu9EAoSw63Hv41K1ie4gD-xRr4bc

<> 2026-08-17T174124.200.json

### поставить лайк посту
POST http://localhost:8083/api/v1/likes/5bcc9f4b-b9c2-43f9-8767-3135fd4a39a9/like
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ3eHJzdCIsInVzZXJJZCI6ImI1ODliZGIyLTQ5YTYtNDczYS1iZDQzLTg0NzA2ZGEwMGNjYyIsImlhdCI6MTc4Njk3NzU1MywiZXhwIjoxNzg5NTY5NTUzfQ.ASch-ROg2ByNZ_SOXaDCu-zaF41zGn-jYUfjIu9EAoSw63Hv41K1ie4gD-xRr4bc

### посмотреть сколько лайков на посте
GET http://localhost:8083/api/v1/likes/5bcc9f4b-b9c2-43f9-8767-3135fd4a39a9/count
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ3eHJzdCIsInVzZXJJZCI6ImI1ODliZGIyLTQ5YTYtNDczYS1iZDQzLTg0NzA2ZGEwMGNjYyIsImlhdCI6MTc4Njk3NzU1MywiZXhwIjoxNzg5NTY5NTUzfQ.ASch-ROg2ByNZ_SOXaDCu-zaF41zGn-jYUfjIu9EAoSw63Hv41K1ie4gD-xRr4bc

<> 2026-08-17T174301.200.json

### оствавить комент посту
POST http://localhost:8083/api/v1/posts/5bcc9f4b-b9c2-43f9-8767-3135fd4a39a9/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ3eHJzdCIsInVzZXJJZCI6ImI1ODliZGIyLTQ5YTYtNDczYS1iZDQzLTg0NzA2ZGEwMGNjYyIsImlhdCI6MTc4Njk3NzU1MywiZXhwIjoxNzg5NTY5NTUzfQ.ASch-ROg2ByNZ_SOXaDCu-zaF41zGn-jYUfjIu9EAoSw63Hv41K1ie4gD-xRr4bc

{
  "content": "крутой пост"
}

<> 2026-08-17T174358.200.json

### посмотреть сколько коментов на посте
GET http://localhost:8083/api/v1/posts/5bcc9f4b-b9c2-43f9-8767-3135fd4a39a9/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ3eHJzdCIsInVzZXJJZCI6ImI1ODliZGIyLTQ5YTYtNDczYS1iZDQzLTg0NzA2ZGEwMGNjYyIsImlhdCI6MTc4Njk3NzU1MywiZXhwIjoxNzg5NTY5NTUzfQ.ASch-ROg2ByNZ_SOXaDCu-zaF41zGn-jYUfjIu9EAoSw63Hv41K1ie4gD-xRr4bc

<> 2026-08-17T174502.200.json