services:
  notification-db:
    image: postgres:16-alpine
    container_name: notification-db-pg
    environment:
      POSTGRES_PASSWORD: notification
      POSTGRES_DB: notification
      POSTGRES_USER: notification
    ports:
      - '5433:5432'
    volumes:
      - notification_postgres_data:/var/lib/postgresql/data

volumes:
  notification_postgres_data: