spring:
  application:
    name: notification-svc
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: true

  datasource:
    password: notification
    username: notification
    url: jdbc:postgresql://localhost:5433/notification
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: notifications

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: public
    liquibase-schema: public

app:
  kafka:
    bootstrap-servers: localhost:9092
    consumer-auto-startup: true
    topics:

      notification-requested:
        topic: social.notification.requested.v1
        partitions: 3
        group-id: notifications.social-events

server:
  port: 8081
