create schema if not exists users;

create table if not exists users.users
(
    id         uuid primary key,
    email      varchar unique not null,
    password   varchar        not null,
    username   varchar unique not null,
    bio        text,
    created_at timestamp      not null default current_timestamp
);

create table if not exists users.roles
(
    id   bigint generated by default as identity primary key,
    name varchar not null unique
);

create table if not exists users.user_roles
(
    user_id uuid references users.users (id),
    role_id bigint references users.roles (id),
    primary key (user_id, role_id)
);
