services:
  social-db:
    image: postgres:16-alpine
    container_name: social-db-pg
    environment:
      POSTGRES_PASSWORD: social
      POSTGRES_DB: social
      POSTGRES_USER: social
    ports:
      - '5439:5432'
    volumes:
      - social_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U social -d social
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  social_postgres_data: