spring:
  application:
    name: user-svc
  main:
    banner-mode: off

  datasource:
    password: user
    username: user
    url: jdbc:postgresql://localhost:5432/user
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: users
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: public
    liquibase-schema: public

app:
  jwt:
    secret: ${JWT_SECRET:asdfjhsadfuyqweuryqwyer987qweroiqwuefohsakjdhfsaheiufyqwer}
    expiration-access: ${EXPIRATION_ACCESS:90000}
    expiration-refresh: ${EXPIRATION_REFRESH:2592000000}
server:
  port: 8080
